apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: navidrome
  name: navidrome
spec:
  type: NodePort
  ports:
    - name: "4533"
      port: 4533
      targetPort: 4533
      nodePort: 30001
  selector:
    io.kompose.service: navidrome
